const billboards = [
    {
        "billboard_id": "SRCN1",
        "route_name": "Westlands",
        "scout_name": "Monica Mwangi",
        "date": "2018-12-23",
        "media_owner": "Others",
        "select_medium": "Wall Wrap",
        "billboard_empty": "No",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Frontlit",
        "zone": "Highway",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Landscape",
        "site_run_up": "150M",
        "condition": "Good",
        "visibility": "Excellent",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchr.blob.core.windows.net/researchrattachments/photo_2018_December_23_a5ccb6.jpg",
        "photo_long_range": "https://researchr.blob.core.windows.net/researchrattachments/photo_2018_December_23_95351d.jpg",
        "height": "Eye Level",
        "lat": "-1.26566350000",
        "long": "36.83506030000",
        "constituency": "Westlands",
        "road_type": "Dual Carriage",
        "user": 1
    },
    {
        "billboard_id": "SRCN2",
        "route_name": "Arboretum Drive",
        "scout_name": "Alice Gathoni",
        "date": "2018-08-27",
        "media_owner": "Ad Site",
        "select_medium": "Self standing",
        "billboard_empty": "No",
        "customer_industry": "<Null>",
        "customer_brand": "<Null>",
        "site_lighting_illumination": "Frontlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "50M",
        "condition": "Good",
        "visibility": "Good",
        "traffic": "Fast",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_27_a52250.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_27_04f55e.jpg",
        "height": "Eye Level",
        "lat": "-1.27698280000",
        "long": "36.80436570000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN3",
        "route_name": "Arboretum Drive",
        "scout_name": "Alice Gathoni",
        "date": "2018-08-23",
        "media_owner": "Others",
        "select_medium": "Self standing",
        "billboard_empty": "No",
        "customer_industry": "Transport",
        "customer_brand": "Others",
        "site_lighting_illumination": "Backlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "NULL",
        "orientation": "Landscape",
        "site_run_up": "100M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_23_ed6230.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_23_49c923.jpg",
        "height": "Eye Level",
        "lat": "-1.27446910000",
        "long": "36.80037440000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN4",
        "route_name": "Arboretum Drive",
        "scout_name": "Alice Gathoni",
        "date": "2018-08-23",
        "media_owner": "Magnate Ventures",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": "<Null>",
        "customer_brand": "<Null>",
        "site_lighting_illumination": "Unlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "100M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Head On",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_23_1c7bb5.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_23_ded735.jpg",
        "height": "Eye Level",
        "lat": "-1.27430890000",
        "long": "36.80122600000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN5",
        "route_name": "Argwings Kodhek Road",
        "scout_name": "Alice Gathoni",
        "date": "2018-08-25",
        "media_owner": "Ad Site",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": "<Null>",
        "customer_brand": "<Null>",
        "site_lighting_illumination": "Frontlit",
        "zone": "Along Street",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "30M",
        "condition": "Good",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_25_4d2174.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_25_0a2633.jpg",
        "height": "Eye Level",
        "lat": "-1.29250000000",
        "long": "36.78048500000",
        "constituency": "Dagoretti North",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN6",
        "route_name": "Argwings Kodhek Road",
        "scout_name": "Alice Gathoni",
        "date": "2018-08-25",
        "media_owner": "Livead",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": "<Null>",
        "customer_brand": "<Null>",
        "site_lighting_illumination": "Frontlit",
        "zone": "Bus Park",
        "direction_from_cbd": "Inbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "30M",
        "condition": "Good",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_25_c7c92a.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_25_3b9a34.jpg",
        "height": "Eye Level",
        "lat": "-1.29231430000",
        "long": "36.78567400000",
        "constituency": "Dagoretti North",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN7",
        "route_name": "Westlands",
        "scout_name": "Monica Mwangi",
        "date": "2018-12-23",
        "media_owner": null,
        "select_medium": "Wall Wrap",
        "billboard_empty": "Yes",
        "customer_industry": "<Null>",
        "customer_brand": "<Null>",
        "site_lighting_illumination": "Unlit",
        "zone": "Highway",
        "direction_from_cbd": "Outbound",
        "size": "12*20",
        "orientation": "Landscape",
        "site_run_up": "50M",
        "condition": "Poor",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchr.blob.core.windows.net/researchrattachments/photo_2018_December_23_d18dec.jpg",
        "photo_long_range": "https://researchr.blob.core.windows.net/researchrattachments/photo_2018_December_23_183bc3.jpg",
        "height": "Eye Level",
        "lat": "-1.26545300000",
        "long": "36.83525750000",
        "constituency": "Westlands",
        "road_type": "Dual Carriage",
        "user": 1
    },
    {
        "billboard_id": "SRCN8",
        "route_name": "Argwings Kodhek Road",
        "scout_name": "Alice Gathoni",
        "date": "2018-08-24",
        "media_owner": "Others",
        "select_medium": "Wall Wrap",
        "billboard_empty": "No",
        "customer_industry": "Foods",
        "customer_brand": "Others",
        "site_lighting_illumination": "Frontlit",
        "zone": "Along Street",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "50M",
        "condition": "Good",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_6226d8.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_0319ea.jpg",
        "height": "Eye Level",
        "lat": "-1.29520590000",
        "long": "36.79922850000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN9",
        "route_name": "Argwings Kodhek Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Ingenious",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Unlit",
        "zone": "Along Street",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "50M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_be7c24.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_d654fd.jpg",
        "height": "Outbound",
        "lat": "-1.29299170000",
        "long": "36.79078830000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN10",
        "route_name": "Argwings Kodhek Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Firmbridge",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Backlit",
        "zone": "Along Street",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "50M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_f8fc08.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_dd5d73.jpg",
        "height": "Outbound",
        "lat": "-1.29317510000",
        "long": "36.79214490000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN11",
        "route_name": "Argwings Kodhek Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Digital Screen",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Backlit",
        "zone": "Bus Park",
        "direction_from_cbd": "Outbound",
        "size": "NULL",
        "orientation": "Landscape",
        "site_run_up": "50M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_1a65f9.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_24_6b09f9.jpg",
        "height": "Outbound",
        "lat": "-1.29483420000",
        "long": "36.79894940000",
        "constituency": "Westlands",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN12",
        "route_name": "Outering road ",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Dimension Media",
        "select_medium": "Self standing",
        "billboard_empty": "No",
        "customer_industry": "Beverage",
        "customer_brand": "Others",
        "site_lighting_illumination": "Frontlit",
        "zone": "Highway",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Good",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_28_ea1fe5.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_28_f1c15a.jpg",
        "height": "Unspecified",
        "lat": "-1.24611570000",
        "long": "36.86859400000",
        "constituency": "Ruaraka",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN13",
        "route_name": "Bunyala Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Single panel backlit",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": null,
        "zone": "Highway",
        "direction_from_cbd": "Inbound",
        "size": "NULL",
        "orientation": "Landscape",
        "site_run_up": "80M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_3a7dc0.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_7f0d9d.jpg",
        "height": "Inbound",
        "lat": "-1.29929630000",
        "long": "36.82422150000",
        "constituency": "Langata",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN14",
        "route_name": "Bunyala Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Magnate Ventures",
        "select_medium": "Sky Sign",
        "billboard_empty": "No",
        "customer_industry": "Household",
        "customer_brand": "Samsung",
        "site_lighting_illumination": "Frontlit",
        "zone": "Highway",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "100M",
        "condition": "Good",
        "visibility": "Excellent",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_9fbf55.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_27dbad.jpg",
        "height": "Outbound",
        "lat": "-1.29985350000",
        "long": "36.82465850000",
        "constituency": "Langata",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN15",
        "route_name": "Bunyala Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Sky Sign",
        "billboard_empty": "No",
        "customer_industry": "Transport",
        "customer_brand": "Others",
        "site_lighting_illumination": "Frontlit",
        "zone": "Highway",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Good",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_85b7e5.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_414be7.jpg",
        "height": "Outbound",
        "lat": "-1.30031210000",
        "long": "36.82458800000",
        "constituency": "Langata",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN16",
        "route_name": "Bunyala Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Unlit",
        "zone": "Highway",
        "direction_from_cbd": "Inbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Excellent",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_d5b43d.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_37914a.jpg",
        "height": "Inbound",
        "lat": "-1.29992810000",
        "long": "36.82307610000",
        "constituency": "Langata",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN17",
        "route_name": "Bunyala Road",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Magnate Ventures",
        "select_medium": "Self standing",
        "billboard_empty": "No",
        "customer_industry": "Financial Services",
        "customer_brand": "Others",
        "site_lighting_illumination": "Frontlit",
        "zone": "Highway",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "100M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_178419.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_31_a94618.jpg",
        "height": "Outbound",
        "lat": "-1.29624830000",
        "long": "36.82276000000",
        "constituency": "Langata",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN18",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Wall Wrap",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Unlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "30M",
        "condition": "Poor",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_533f4f.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_1d54d1.jpg",
        "height": "Unspecified",
        "lat": "-1.28175910000",
        "long": "36.83188790000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN19",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Double Panel Bill board",
        "billboard_empty": "No",
        "customer_industry": "Financial Services",
        "customer_brand": "Safaricom",
        "site_lighting_illumination": "Backlit",
        "zone": "Bus Park",
        "direction_from_cbd": "Unspecified",
        "size": "12*20",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_e7a5e7.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_4f0b39.jpg",
        "height": "Unspecified",
        "lat": "-1.28945330000",
        "long": "36.82747500000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN20",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Backlite",
        "select_medium": "Double Panel Bill board",
        "billboard_empty": "No",
        "customer_industry": "Financial Services",
        "customer_brand": "Others",
        "site_lighting_illumination": "Backlit",
        "zone": "Along Street",
        "direction_from_cbd": "Outbound",
        "size": "12*20",
        "orientation": "Landscape",
        "site_run_up": "150M",
        "condition": "Excellent",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_2cef38.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_6fc45d.jpg",
        "height": "Outbound",
        "lat": "-1.29316410000",
        "long": "36.82104640000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN21",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Wall Wrap",
        "billboard_empty": "No",
        "customer_industry": "Financial Services",
        "customer_brand": "Others",
        "site_lighting_illumination": "Unlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*30",
        "orientation": "Landscape",
        "site_run_up": "30M",
        "condition": "Poor",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_7066b3.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_d33aa7.jpg",
        "height": "Unspecified",
        "lat": "-1.28825360000",
        "long": "36.82963100000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN22",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Magnate Ventures",
        "select_medium": "Light Mast",
        "billboard_empty": "No",
        "customer_industry": "Communications",
        "customer_brand": "Others",
        "site_lighting_illumination": null,
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Good",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_eac8c9.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_3987c4.jpg",
        "height": "Unspecified",
        "lat": "-1.27796910000",
        "long": "36.83474000000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN23",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Magnate Ventures",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Frontlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "30M",
        "condition": "Good",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_5523a1.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_6a3487.jpg",
        "height": "Unspecified",
        "lat": "-1.27734330000",
        "long": "36.83493190000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN24",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Magnate Ventures",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Frontlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Excellent",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_b7b6aa.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_55170b.jpg",
        "height": "Unspecified",
        "lat": "-1.28590860000",
        "long": "36.83237450000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN25",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Ad Site",
        "select_medium": "Self standing",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Frontlit",
        "zone": "Bus Park",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "80M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_e1b2ba.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_970386.jpg",
        "height": "Unspecified",
        "lat": "-1.28563090000",
        "long": "36.83536750000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN26",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Sky Sign",
        "billboard_empty": "No",
        "customer_industry": "Tourism And Entertainment",
        "customer_brand": "Others",
        "site_lighting_illumination": "Backlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "NULL",
        "orientation": "Landscape",
        "site_run_up": "50M",
        "condition": "Excellent",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Right",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_b915a6.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_540d9a.jpg",
        "height": "Unspecified",
        "lat": "-1.28477770000",
        "long": "36.83096800000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN27",
        "route_name": "Kamkunji",
        "scout_name": "Elvis Omete",
        "date": "1970-01-01",
        "media_owner": "Magnate Ventures",
        "select_medium": "Self standing",
        "billboard_empty": "NO",
        "customer_industry": "Personal Care",
        "customer_brand": "Others",
        "site_lighting_illumination": "Frontlit",
        "zone": "Highway",
        "direction_from_cbd": "Outbound",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "100M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Fast",
        "angle": "Left",
        "photo": "https://researchr.blob.core.windows.net/researchrattachments/photo_2018_December_24_db4636.jpg",
        "photo_long_range": "https://researchr.blob.core.windows.net/researchrattachments/photo_2018_December_24_b69e4f.jpg",
        "height": "Outbound",
        "lat": "-1.27391510000",
        "long": "36.81037240000",
        "constituency": "Kamkunji",
        "road_type": "Dual Carriage",
        "user": 1
    },
    {
        "billboard_id": "SRCN28",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Wall Wrap",
        "billboard_empty": "No",
        "customer_industry": "Communications",
        "customer_brand": "Telkom",
        "site_lighting_illumination": "Frontlit",
        "zone": "Along Street",
        "direction_from_cbd": "Inbound",
        "size": "12*30",
        "orientation": "Potrait",
        "site_run_up": "50M",
        "condition": "Excellent",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_b60d10.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_235618.jpg",
        "height": "Inbound",
        "lat": "-1.29010380000",
        "long": "36.82546850000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN29",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Sky Sign",
        "billboard_empty": "Yes",
        "customer_industry": null,
        "customer_brand": null,
        "site_lighting_illumination": "Unlit",
        "zone": "Along Street",
        "direction_from_cbd": "Unspecified",
        "size": "12*10",
        "orientation": "Potrait",
        "site_run_up": "50M",
        "condition": "Good",
        "visibility": "Poor",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_6ab9d8.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_27c024.jpg",
        "height": "Unspecified",
        "lat": "-1.28385240000",
        "long": "36.83148990000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    },
    {
        "billboard_id": "SRCN30",
        "route_name": "CBD",
        "scout_name": "Alice Gathoni",
        "date": "1970-01-01",
        "media_owner": "Others",
        "select_medium": "Double Panel Bill board",
        "billboard_empty": "No",
        "customer_industry": "Personal Care",
        "customer_brand": "Others",
        "site_lighting_illumination": "Backlit",
        "zone": "Along Street",
        "direction_from_cbd": "Outbound",
        "size": "12*20",
        "orientation": "Landscape",
        "site_run_up": "100M",
        "condition": "Excellent",
        "visibility": "Good",
        "traffic": "Average",
        "angle": "Left",
        "photo": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_77a18b.jpg",
        "photo_long_range": "https://researchrpoc.blob.core.windows.net/researchrpocattachments/photo_2018_August_30_846cd0.jpg",
        "height": "Outbound",
        "lat": "-1.29398030000",
        "long": "36.82137230000",
        "constituency": "Kamkunji",
        "road_type": "Single Lane",
        "user": 1
    }
]